
//HEADERS
export const REQUEST_ID_HEADER = "X-COREOS-REQUEST-ID";
export const TENANT_ID_HEADER = "X-COREOS-TID";
export const AUTH_TOKEN_HEADER = "X-COREOS-AUTH";
export const ACCESS_TOKEN_HEADER = "X-COREOS-ACCESS";